"""
Generated by Claude

btw_education.py - Vote choice by education group in German federal elections
==============================================================================

What this script does
---------------------
1. Scrapes the election analysis overview of Forschungsgruppe Wahlen
   (https://www.forschungsgruppe.de/Wahlen/Wahlanalysen/) and downloads the
   "Kurzanalyse" PDF of every Bundestag election (Bundestagswahl) from the most
   recent one back to and including 2013 (configurable via --min-year).
   PDFs are stored in ../../data/raw/Kurzanalysen_ForschergruppeWahlen and are
   only downloaded if the file does not exist yet.

2. Extracts the chart "Wahlentscheidung in den Bildungsgruppen" (vote choice
   by education group) from every downloaded PDF and writes one tidy table to
   ../../data/interim/btw_education.csv with the columns
       Datum | Bildungsgruppe | CDU/CSU | SPD | Grüne | FDP | Linke | AfD | BSW | Sonstige
   PDFs that do not contain this chart (e.g. 2017) are skipped.

Important notes
---------------
* The charts are stacked horizontal bar charts and the layout differs between
  years (left/right page column, party order, colours, set of parties, number
  labels that are missing for very small segments). Reading the numbers in
  text order would therefore shift values to the wrong party. Instead, every
  number is assigned to the coloured bar segment it is printed on, and the
  colour is mapped to a party via the chart legend.
* Values are percentages as printed in the PDF. Segments that are too small to
  carry a label in the PDF, and parties that did not run / were not shown,
  are left empty (NaN).
* The "Wahlergebnis" row (official overall result shown as reference bar in
  each chart) is not an education group and is therefore dropped.
* Paths are resolved relative to this file, so the script can be started from
  any working directory:  python src/scraping/btw_education.py

Dependencies: requests, beautifulsoup4, pdfplumber, pandas
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from urllib.parse import urljoin

import pandas as pd
import pdfplumber
import requests
from bs4 import BeautifulSoup

# --------------------------------------------------------------------------
# Configuration
# --------------------------------------------------------------------------

BASE_URL = "https://www.forschungsgruppe.de/Wahlen/Wahlanalysen/"

SCRIPT_DIR = Path(__file__).resolve().parent
RAW_DIR = (SCRIPT_DIR / "../../data/raw/Kurzanalysen_ForschergruppeWahlen").resolve()
INTERIM_DIR = (SCRIPT_DIR / "../../data/interim").resolve()
OUTPUT_CSV = INTERIM_DIR / "btw_education.csv"

# Oldest election year that is downloaded and parsed (inclusive).
DEFAULT_MIN_YEAR = 2013

# File name pattern of the downloaded PDFs; the election year is encoded in
# the name so that existing files can be recognised without the website.
PDF_NAME_TEMPLATE = "Bundestagswahl_{year}_Kurzanalyse.pdf"
PDF_NAME_REGEX = re.compile(r"^Bundestagswahl_(\d{4})_Kurzanalyse\.pdf$")

CHART_TITLE_REGEX = r"Wahlentscheidung\s+in\s+den\s+Bildungsgruppen"

PARTY_COLUMNS = ["CDU/CSU", "SPD", "Grüne", "FDP", "Linke", "AfD", "BSW", "Sonstige"]
OUTPUT_COLUMNS = ["Datum", "Bildungsgruppe", *PARTY_COLUMNS]

# Maps the (normalised, upper-case, whitespace-free) legend labels used in the
# different PDFs onto the canonical column names.
PARTY_ALIASES = {
    "CDU/CSU": "CDU/CSU",
    "CDU": "CDU/CSU",
    "UNION": "CDU/CSU",
    "SPD": "SPD",
    "GRÜNE": "Grüne",
    "GRUENE": "Grüne",
    "B90/GRÜNE": "Grüne",
    "BÜNDNIS90/DIEGRÜNE": "Grüne",
    "FDP": "FDP",
    "LINKE": "Linke",
    "DIELINKE": "Linke",
    "LINKE.PDS": "Linke",
    "PDS": "Linke",
    "AFD": "AfD",
    "BSW": "BSW",
    "SONSTIGE": "Sonstige",
    "ANDERE": "Sonstige",
}

# Older PDFs use shorter row labels; harmonise them with the newer wording.
EDUCATION_GROUP_ALIASES = {
    "Hauptschule": "Hauptschulabschluss",
    "Hochschule": "Hochschulabschluss",
}

# Chart rows that are no education group (overall result used as reference bar).
EXCLUDED_GROUPS = {"Wahlergebnis"}

# Official election dates, only used if no date can be read from the PDF.
FALLBACK_ELECTION_DATES = {
    2002: "2002-09-22",
    2005: "2005-09-18",
    2009: "2009-09-27",
    2013: "2013-09-22",
    2017: "2017-09-24",
    2021: "2021-09-26",
    2025: "2025-02-23",
}

HTTP_HEADERS = {"User-Agent": "Mozilla/5.0 (compatible; btw-education-scraper/1.0)"}
HTTP_TIMEOUT = 30

# Geometry thresholds in PDF points (1/72 inch).
LEGEND_SQUARE_MAX_SIZE = 7.0  # legend colour squares are ~4.7 pt wide/high
BAR_MIN_HEIGHT = 8.0  # bar segments are ~13-15 pt high
ROW_TOP_TOLERANCE = 4.0  # segments whose tops differ less belong to one bar
COLOR_TOLERANCE = 0.03  # max. difference per RGB channel for "same colour"
CHART_MAX_HEIGHT = 220.0  # fallback chart height if no source line is found


# --------------------------------------------------------------------------
# Part 1: Download
# --------------------------------------------------------------------------


def find_btw_pdf_links(min_year: int) -> dict[int, str]:
    """Return {election_year: pdf_url} for all Bundestag elections >= min_year.

    The overview page contains one table row per election: the first cell holds
    the election name (e.g. "Bundestagswahl 2021"), the second cell the link
    labelled "Kurzanalyse".
    """
    response = requests.get(BASE_URL, headers=HTTP_HEADERS, timeout=HTTP_TIMEOUT)
    response.raise_for_status()
    soup = BeautifulSoup(response.text, "html.parser")

    links: dict[int, str] = {}
    for row in soup.find_all("tr"):
        cells = row.find_all("td")
        if len(cells) < 2:
            continue

        name = " ".join(cells[0].get_text(" ", strip=True).split())
        match = re.fullmatch(r"Bundestagswahl\s+(\d{4})", name)
        if not match:
            continue
        year = int(match.group(1))
        if year < min_year:
            continue

        # Prefer the link explicitly called "Kurzanalyse", otherwise take the first PDF link.
        pdf_links = [a for a in row.find_all("a", href=True) if ".pdf" in a["href"].lower()]
        kurzanalyse = [a for a in pdf_links if "kurzanalyse" in a.get_text(strip=True).lower()]
        chosen = (kurzanalyse or pdf_links or [None])[0]
        if chosen is None:
            print(f"  [warn] No PDF link found for Bundestagswahl {year}")
            continue

        # Strip session ids such as ";jsessionid=..." that are sometimes appended.
        href = chosen["href"].split(";")[0]
        links[year] = urljoin(BASE_URL, href)

    return dict(sorted(links.items(), reverse=True))


def download_pdf(url: str, target: Path) -> None:
    """Download a PDF to `target` (via a temporary file, so aborted downloads leave no broken PDF)."""
    response = requests.get(url, headers=HTTP_HEADERS, timeout=HTTP_TIMEOUT)
    response.raise_for_status()
    if not response.content.startswith(b"%PDF"):
        raise ValueError(f"Response from {url} is not a PDF")

    tmp_path = target.with_suffix(target.suffix + ".part")
    tmp_path.write_bytes(response.content)
    tmp_path.replace(target)


def download_kurzanalysen(min_year: int) -> None:
    """Download all missing Kurzanalyse PDFs of Bundestag elections >= min_year."""
    RAW_DIR.mkdir(parents=True, exist_ok=True)
    print(f"Fetching election overview: {BASE_URL}")

    try:
        links = find_btw_pdf_links(min_year)
    except requests.RequestException as exc:
        # Without the website we can still parse PDFs that were downloaded earlier.
        print(f"  [warn] Could not load overview page ({exc}); using existing files only.")
        return

    if not links:
        print("  [warn] No Bundestag election PDFs found on the overview page.")
        return

    for year, url in links.items():
        target = RAW_DIR / PDF_NAME_TEMPLATE.format(year=year)
        if target.exists():
            print(f"  [skip] {year}: {target.name} already exists")
            continue
        try:
            download_pdf(url, target)
            print(f"  [done] {year}: downloaded {url} -> {target.name}")
        except (requests.RequestException, ValueError) as exc:
            print(f"  [error] {year}: download of {url} failed ({exc})")


# --------------------------------------------------------------------------
# Part 2: Extraction
# --------------------------------------------------------------------------


@dataclass
class Box:
    """Axis-aligned rectangle in PDF page coordinates (top < bottom)."""

    x0: float
    x1: float
    top: float
    bottom: float

    @property
    def cx(self) -> float:
        return (self.x0 + self.x1) / 2

    @property
    def cy(self) -> float:
        return (self.top + self.bottom) / 2

    def contains_x(self, x: float, tol: float = 0.0) -> bool:
        return self.x0 - tol <= x <= self.x1 + tol

    def contains(self, x: float, y: float, tol: float = 0.0) -> bool:
        return self.contains_x(x, tol) and self.top - tol <= y <= self.bottom + tol


@dataclass
class Segment(Box):
    """One coloured part of a stacked bar."""

    party: str = ""


@dataclass
class BarRow(Box):
    """One horizontal bar (= one education group) of the chart."""

    segments: list[Segment] = field(default_factory=list)


def to_rgb(color) -> tuple[float, float, float] | None:
    """Normalise a pdfplumber colour (gray, RGB or CMYK) to an RGB tuple."""
    if color is None or isinstance(color, str):
        return None
    if isinstance(color, (int, float)):
        color = (color,)
    color = tuple(float(c) for c in color if isinstance(c, (int, float)))
    if len(color) == 1:
        return (color[0],) * 3
    if len(color) == 3:
        return color  # type: ignore[return-value]
    if len(color) == 4:
        c, m, y, k = color
        return ((1 - c) * (1 - k), (1 - m) * (1 - k), (1 - y) * (1 - k))
    return None


def same_color(a, b) -> bool:
    return a is not None and b is not None and all(abs(x - y) <= COLOR_TOLERANCE for x, y in zip(a, b))


def is_white(color) -> bool:
    return same_color(color, (1.0, 1.0, 1.0))


def normalise_party(label: str) -> str | None:
    """Map a legend label (e.g. 'GRÜNE', 'Linke') to the canonical column name."""
    key = re.sub(r"\s+", "", label).upper()
    return PARTY_ALIASES.get(key)


def parse_number(text: str) -> float | None:
    """Convert German number strings such as '16,4' to floats."""
    text = text.strip()
    if not re.fullmatch(r"\d+(?:[.,]\d+)?", text):
        return None
    return float(text.replace(",", "."))


def filled_shapes(page) -> list[tuple[Box, tuple[float, float, float] | None]]:
    """All filled rectangles and closed curves of a page with their fill colour.

    Some PDFs (e.g. 2013) draw individual bar segments as curves instead of
    rectangles, so both object types are considered via their bounding box.
    """
    shapes = []
    for obj in list(page.rects) + list(page.curves):
        if not obj.get("fill"):
            continue
        box = Box(obj["x0"], obj["x1"], obj["top"], obj["bottom"])
        shapes.append((box, to_rgb(obj.get("non_stroking_color"))))
    return shapes


def locate_chart(pdf) -> tuple[object, Box] | None:
    """Find the page and the bounding box of the education chart.

    Returns None if the PDF does not contain the chart. The box spans the page
    column of the title, from the title down to the chart's source line
    ("Forschungsgruppe Wahlen: Befragung am Wahltag ...").
    """
    for page in pdf.pages:
        hits = page.search(CHART_TITLE_REGEX, regex=True, case=False)
        if not hits:
            continue
        title = hits[0]

        # The newsletters use a two-column layout; the chart lives in the title's column.
        half = page.width / 2
        if title["x0"] < half:
            x0, x1 = 0.0, half
        else:
            x0, x1 = half, float(page.width)

        # The chart ends at its source line (or at the next chart title).
        bottom = min(title["bottom"] + CHART_MAX_HEIGHT, float(page.height))
        for word in page.extract_words():
            if (
                word["top"] > title["bottom"] + 20
                and x0 <= word["x0"] < x1
                and word["text"] in ("Forschungsgruppe", "Wahlentscheidung")
            ):
                bottom = min(bottom, word["bottom"] + 1)
        return page, Box(x0, x1, title["top"], bottom)

    return None


def read_legend(shapes, words, chart: Box, first_bar_top: float) -> list[tuple[tuple, str]]:
    """Return [(rgb, party)] from the small colour squares of the legend.

    Each legend entry is a small coloured square followed by the party name;
    the text between one square and the next is taken as the label.
    """
    squares = [
        (box, rgb)
        for box, rgb in shapes
        if rgb is not None
        and box.x1 - box.x0 <= LEGEND_SQUARE_MAX_SIZE
        and box.bottom - box.top <= LEGEND_SQUARE_MAX_SIZE
        and chart.contains(box.cx, box.cy)
        and box.bottom <= first_bar_top
    ]
    squares.sort(key=lambda s: (round(s[0].top), s[0].x0))

    legend = []
    for i, (box, rgb) in enumerate(squares):
        next_x0 = chart.x1
        if i + 1 < len(squares) and abs(squares[i + 1][0].cy - box.cy) < 3:
            next_x0 = squares[i + 1][0].x0
        label_words = [
            w["text"]
            for w in words
            if box.x1 - 1 <= w["x0"] < next_x0 and abs((w["top"] + w["bottom"]) / 2 - box.cy) < 5
        ]
        party = normalise_party(" ".join(label_words))
        if party is None:
            print(f"    [warn] Unknown legend label '{' '.join(label_words)}' ignored")
            continue
        legend.append((rgb, party))
    return legend


def build_bar_rows(shapes, chart: Box, legend) -> list[BarRow]:
    """Group legend-coloured bar segments into horizontal bars (one per row)."""
    segments = []
    for box, rgb in shapes:
        if box.bottom - box.top < BAR_MIN_HEIGHT or not chart.contains(box.cx, box.cy):
            continue
        party = next((p for c, p in legend if same_color(c, rgb)), None)
        if party is not None:
            segments.append(Segment(box.x0, box.x1, box.top, box.bottom, party=party))

    rows: list[BarRow] = []
    for seg in sorted(segments, key=lambda s: (s.top, s.x0)):
        if rows and abs(rows[-1].top - seg.top) < ROW_TOP_TOLERANCE:
            row = rows[-1]
            row.segments.append(seg)
            row.x0, row.x1 = min(row.x0, seg.x0), max(row.x1, seg.x1)
            row.bottom = max(row.bottom, seg.bottom)
        else:
            rows.append(BarRow(seg.x0, seg.x1, seg.top, seg.bottom, segments=[seg]))
    return rows


def read_row_values(row: BarRow, chars, white_boxes: list[Box]) -> dict[str, float]:
    """Read the numbers printed on one bar and assign them to parties.

    Numbers are printed on small white label boxes. Grouping characters by
    label box splits labels that touch each other (pdfplumber would otherwise
    merge e.g. '8,8' '4,97' '4,6' into one word). Characters without a label
    box are grouped by their horizontal distance.
    """
    row_chars = sorted(
        (
            c
            for c in chars
            if row.top <= (c["top"] + c["bottom"]) / 2 <= row.bottom
            and row.contains_x((c["x0"] + c["x1"]) / 2, tol=3)
            and c["text"] in "0123456789,."
        ),
        key=lambda c: c["x0"],
    )
    row_boxes = [b for b in white_boxes if row.contains(b.cx, b.cy)]

    def box_index(char) -> int | None:
        cx, cy = (char["x0"] + char["x1"]) / 2, (char["top"] + char["bottom"]) / 2
        return next((i for i, b in enumerate(row_boxes) if b.contains(cx, cy)), None)

    # Build number tokens: [[chars...], ...]
    tokens: list[list[dict]] = []
    prev_box: int | None = None
    for char in row_chars:
        idx = box_index(char)
        if tokens:
            prev = tokens[-1][-1]
            same_box = idx is not None and idx == prev_box
            touching = idx is None and prev_box is None and char["x0"] - prev["x1"] < 1.0
            if same_box or touching:
                tokens[-1].append(char)
                continue
        tokens.append([char])
        prev_box = idx

    values: dict[str, float] = {}
    for token in tokens:
        text = "".join(c["text"] for c in token)
        value = parse_number(text)
        if value is None:
            continue
        cx = (token[0]["x0"] + token[-1]["x1"]) / 2

        # Segment under the label; if the label sticks out, take the nearest segment.
        segment = next((s for s in row.segments if s.contains_x(cx)), None)
        if segment is None:
            segment = min(row.segments, key=lambda s: min(abs(s.x0 - cx), abs(s.x1 - cx)))
        if segment.party in values:
            print(f"    [warn] Second value {text} for {segment.party} ignored")
            continue
        values[segment.party] = value
    return values


def read_row_label(row: BarRow, rows: list[BarRow], words) -> str:
    """Return the education group label printed left of a bar.

    Labels can span two lines ("Hauptschul-" / "abschluss"), so every word left
    of the bars is assigned to the vertically closest bar.
    """
    bars_x0 = min(r.x0 for r in rows)
    label_words = []
    for w in words:
        if w["x1"] > bars_x0 + 1:
            continue
        cy = (w["top"] + w["bottom"]) / 2
        if not (rows[0].top - 6 <= cy <= rows[-1].bottom + 6):
            continue
        nearest = min(rows, key=lambda r: abs(r.cy - cy))
        if nearest is row:
            label_words.append(w)

    label_words.sort(key=lambda w: (round(w["top"]), w["x0"]))
    label = " ".join(w["text"] for w in label_words)
    label = re.sub(r"-\s+(?=[a-zäöü])", "", label)  # join hyphenated line breaks
    label = " ".join(label.split())
    return EDUCATION_GROUP_ALIASES.get(label, label)


def read_election_date(page, chart: Box, pdf, year: int) -> str:
    """Return the election date (ISO format) from the chart's source line.

    Falls back to the whole document text and finally to the known official
    election date of that year.
    """
    candidates = [page.crop((chart.x0, chart.top, chart.x1, chart.bottom)).extract_text() or ""]
    candidates.append("\n".join(p.extract_text() or "" for p in pdf.pages))
    for text in candidates:
        for day, month, yyyy in re.findall(r"Wahltag[^\d]{0,40}(\d{1,2})\.(\d{1,2})\.(\d{4})", text):
            if int(yyyy) == year:
                return f"{yyyy}-{int(month):02d}-{int(day):02d}"
    return FALLBACK_ELECTION_DATES.get(year, f"{year}")


def extract_education_table(pdf_path: Path, year: int) -> pd.DataFrame | None:
    """Extract the education chart of one PDF; returns None if it is missing."""
    with pdfplumber.open(pdf_path) as pdf:
        located = locate_chart(pdf)
        if located is None:
            print(f"  [skip] {pdf_path.name}: no 'Wahlentscheidung in den Bildungsgruppen' chart")
            return None
        page, chart = located

        shapes = filled_shapes(page)
        words = [
            w for w in page.extract_words() if chart.contains((w["x0"] + w["x1"]) / 2, (w["top"] + w["bottom"]) / 2)
        ]

        # The legend sits above the first bar; bars are the tall shapes in the chart.
        tall = [b for b, rgb in shapes if b.bottom - b.top >= BAR_MIN_HEIGHT and chart.contains(b.cx, b.cy)]
        legend_limit = min((b.top for b in tall if b.top > chart.top + 15), default=chart.bottom)
        legend = read_legend(shapes, words, chart, legend_limit)
        if not legend:
            print(f"  [skip] {pdf_path.name}: chart found, but no legend could be read")
            return None

        rows = build_bar_rows(shapes, chart, legend)
        if not rows:
            print(f"  [skip] {pdf_path.name}: chart found, but no bars could be read")
            return None

        white_boxes = [b for b, rgb in shapes if is_white(rgb) and b.bottom - b.top < BAR_MIN_HEIGHT * 2]
        date = read_election_date(page, chart, pdf, year)

        records = []
        for row in rows:
            # All rows are still needed above to assign two-line labels to the right bar.
            label = read_row_label(row, rows, words)
            if label in EXCLUDED_GROUPS:
                continue
            values = read_row_values(row, page.chars, white_boxes)
            missing = [s.party for s in row.segments if s.party not in values]
            if missing:
                print(f"    [info] {year} / {label}: no printed value for {', '.join(missing)} (left empty)")
            records.append({"Datum": date, "Bildungsgruppe": label, **values})

    parties = ", ".join(p for _, p in legend)
    print(f"  [done] {pdf_path.name}: {len(records)} rows, date {date}, parties: {parties}")
    return pd.DataFrame.from_records(records)


def build_education_csv(min_year: int) -> pd.DataFrame:
    """Parse all downloaded PDFs (>= min_year) and write the combined CSV."""
    print(f"Extracting education charts from {RAW_DIR}")

    pdfs = []
    for path in RAW_DIR.glob("*.pdf"):
        match = PDF_NAME_REGEX.match(path.name)
        if match and int(match.group(1)) >= min_year:
            pdfs.append((int(match.group(1)), path))

    frames = []
    for year, path in sorted(pdfs):
        try:
            frame = extract_education_table(path, year)
        except Exception as exc:  # a single broken PDF must not stop the whole run
            print(f"  [error] {path.name}: extraction failed ({exc})")
            continue
        if frame is not None:
            frames.append(frame)

    table = pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()
    table = table.reindex(columns=OUTPUT_COLUMNS)

    INTERIM_DIR.mkdir(parents=True, exist_ok=True)
    table.to_csv(OUTPUT_CSV, index=False, float_format="%g", encoding="utf-8")
    print(f"Saved {len(table)} rows from {len(frames)} elections to {OUTPUT_CSV}")
    return table


# --------------------------------------------------------------------------
# Entry point
# --------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    parser.add_argument(
        "--min-year",
        type=int,
        default=DEFAULT_MIN_YEAR,
        help=f"oldest Bundestag election to include (default: {DEFAULT_MIN_YEAR})",
    )
    args = parser.parse_args()

    download_kurzanalysen(args.min_year)
    table = build_education_csv(args.min_year)
    if not table.empty:
        print(table.to_string(index=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
