"""
Generated by Claude

What this script does:
1. Looks up the download link of the time series "Zweitstimmen nach Geschlecht
   und Altersgruppen" (since 1953, representative election statistics) on the
   website of the Bundeswahlleiterin and downloads the CSV file to
   ../../data/raw (relative to this script). If the file already exists
   there, the download is skipped.
2. Reads the raw CSV, keeps only federal elections from 2013 onwards, merges
   the results of CDU and CSU into one column "CDU/CSU" and writes a clean
   table with the schema
       Jahr | Geschlecht | Altersgruppe | CDU/CSU | SPD | Grüne | FDP | Linke | AfD | Sonstige
   to ../../data/interim as a CSV file.

Notes on the data:
- Values are shares of second votes in percent.
- Gender values are kept as in the source: "m", "w", "Summe" and, from 2021
  onwards, "m|d|o" (men incl. diverse / no entry).
- Age groups overlap (e.g. "Summe", ">=60", "60-69", ">=70"), so rows must not
  be added up across age groups.
"""

import html
import re
from pathlib import Path
from urllib.parse import urljoin

import pandas as pd
import requests

PAGE_URL = (
    "https://www.bundeswahlleiterin.de/bundestagswahlen/2025/ergebnisse/"
    "repraesentative-wahlstatistik.html"
)
CSV_FILENAME = "btw_rws_zwst-1953.csv"
MIN_YEAR = 2013

SCRIPT_DIR = Path(__file__).resolve().parent
RAW_DIR = (SCRIPT_DIR / "../../data/raw").resolve()
INTERIM_DIR = (SCRIPT_DIR / "../../data/interim").resolve()
OUTPUT_FILENAME = "btw_gender_age.csv"

HEADERS = {"User-Agent": "Mozilla/5.0 (compatible; btw-gender-age-script)"}

OUTPUT_COLUMNS = [
    "Jahr", "Geschlecht", "Altersgruppe",
    "CDU/CSU", "SPD", "Grüne", "FDP", "Linke", "AfD", "Sonstige",
]


def find_csv_url() -> str:
    """Find the current CSV download link on the results page."""
    print(f"Fetching page: {PAGE_URL}")
    response = requests.get(PAGE_URL, headers=HEADERS, timeout=30)
    response.raise_for_status()
    # The file sits under a hashed path, so the link has to be looked up.
    matches = re.findall(rf'href="([^"]*{re.escape(CSV_FILENAME)})"', response.text)
    if not matches:
        raise RuntimeError(f"No link to {CSV_FILENAME} found on the page.")
    url = urljoin(PAGE_URL, html.unescape(matches[0]))
    print(f"Found CSV link: {url}")
    return url


def download_csv(url: str) -> Path:
    """Download the CSV file and store it unchanged in the raw data folder."""
    RAW_DIR.mkdir(parents=True, exist_ok=True)
    target = RAW_DIR / CSV_FILENAME
    response = requests.get(url, headers=HEADERS, timeout=60)
    response.raise_for_status()
    target.write_bytes(response.content)
    print(f"Saved raw file: {target} ({len(response.content) / 1024:.1f} kB)")
    return target


def read_raw_csv(path: Path) -> pd.DataFrame:
    """Read the raw CSV (comment header, ';' separator, decimal comma)."""
    for encoding in ("utf-8-sig", "cp1252"):
        try:
            return pd.read_csv(
                path, sep=";", decimal=",", comment="#", encoding=encoding
            )
        except UnicodeDecodeError:
            continue
    raise RuntimeError(f"Could not decode {path}")


def build_table(raw: pd.DataFrame) -> pd.DataFrame:
    """Filter elections, merge CDU and CSU and bring columns into the target schema."""
    df = raw.copy()
    # Column 3 is named "Altersgruppe etwa von ... bis ... Jahren" in the source.
    df.columns = ["Jahr", "Geschlecht", "Altersgruppe"] + list(df.columns[3:])
    df = df.rename(columns={"GRÜNE": "Grüne", "PDS/Die Linke": "Linke"})

    df = df[df["Jahr"] >= MIN_YEAR].copy()
    print(f"Rows for elections from {MIN_YEAR} onwards: {len(df)}")

    # CDU and CSU are reported separately from 1961 onwards; add them up.
    df["CDU/CSU"] = df[["CDU", "CSU"]].sum(axis=1, min_count=1).round(1)

    df = df[OUTPUT_COLUMNS].reset_index(drop=True)
    df["Jahr"] = df["Jahr"].astype(int)
    return df


def main() -> None:
    raw_path = RAW_DIR / CSV_FILENAME
    if raw_path.exists():
        print(f"Raw file already exists, skipping download: {raw_path}")
    else:
        csv_url = find_csv_url()
        raw_path = download_csv(csv_url)

    table = build_table(read_raw_csv(raw_path))

    INTERIM_DIR.mkdir(parents=True, exist_ok=True)
    out_path = INTERIM_DIR / OUTPUT_FILENAME
    table.to_csv(out_path, index=False, encoding="utf-8")
    print(f"Saved interim table: {out_path}")
    print(f"Elections included: {sorted(table['Jahr'].unique().tolist())}")
    print(table.head())


if __name__ == "__main__":
    main()