"""
Generated by Claude

ARD-DeutschlandTrend: satisfaction with the German federal government
======================================================================

What this script does
---------------------
1. Download
   Crawls https://www.tagesschau.de/inland/deutschlandtrend (current year(s))
   and every yearly archive page (.../deutschlandtrend/archiv/<year>, from
   2013 on). The PDF links ("Alle Grafiken zum Download") are collected from
   those listing pages and from every DeutschlandTrend article linked there.
   All PDFs published from the February 2013 edition onwards are saved to
   ../../data/raw/deutschlandtrend (relative to this file). Files that already
   exist are not downloaded again.

2. Extraction
   Every PDF in that folder is searched for the question
   "Wie zufrieden sind Sie mit der Arbeit der Bundesregierung?". The values
   for "sehr zufrieden", "zufrieden", "weniger zufrieden" and
   "gar nicht zufrieden" are written to ../../data/interim/regierungszufriedenheit.csv
   with the schema:

       Datum | sehr zufrieden | zufrieden | weniger zufrieden | gar nicht zufrieden

   "Datum" is the last day of the survey period ("Erhebungszeitraum").
   PDFs without the question (e.g. state polls, special editions) are skipped,
   as are PDFs that only report aggregated values (e.g. April 2018).

Important notes
---------------
* The PDF layout changed several times since 2013 (portrait/landscape,
  rotated pages, one or two slides per page, an additional chart with party
  supporters on the same slide, ...). The values are therefore located by
  their position: the number standing directly above each category label is
  taken as the value of that category.
* Some PDFs from 2013 - 2015 contain the chart only as a raster image, i.e.
  the numbers are not available as text. The changes to the previous edition
  ("(+4)", "Angaben in Klammern: Vergleich zu ...") are still text, so these
  values are reconstructed as "values of the reference edition + changes".
  Without a reference edition the bar heights are measured on the rendered
  page and scaled to 100 % minus "weiß nicht" (only used for May 2013). The
  bar heights also serve as a cross-check for the reconstructed values.
* The February 2013 edition was published on 31 January 2013, so the
  download cutoff is based on the publication date of that edition.
* Values of the same survey (same end date) found in several PDFs are only
  stored once.

Usage
-----
    pip install -r requirements.txt
    python src/scraping/regierungszufriedenheit.py              # download + extract
    python src/scraping/regierungszufriedenheit.py --no-download  # extract only

Dependencies: requests, beautifulsoup4, pymupdf
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
import time
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path
from statistics import median
from urllib.parse import urljoin, urlparse

import pymupdf
import requests
from bs4 import BeautifulSoup

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

BASE_URL = "https://www.tagesschau.de"
OVERVIEW_URL = f"{BASE_URL}/inland/deutschlandtrend"
ARCHIVE_URL = f"{OVERVIEW_URL}/archiv/{{year}}"

# First archive year to crawl and earliest publication date of a PDF to download
# (the DeutschlandTrend "Februar 2013" was published on 31 January 2013).
FIRST_YEAR = 2013
MIN_PUBLICATION_DATE = date(2013, 1, 31)

# All paths are resolved relative to this file, so the script can be started
# from any working directory.
SCRIPT_DIR = Path(__file__).resolve().parent
RAW_DIR = (SCRIPT_DIR / "../../data/raw/deutschlandtrend").resolve()
INTERIM_DIR = (SCRIPT_DIR / "../../data/interim").resolve()
OUTPUT_CSV = INTERIM_DIR / "regierungszufriedenheit.csv"

# Be polite to the server: pause between two requests (seconds).
REQUEST_DELAY = 0.3
REQUEST_TIMEOUT = 60
MAX_RETRIES = 3
USER_AGENT = "Mozilla/5.0 (compatible; regierungszufriedenheit-scraper/1.0)"

CSV_HEADER = ["Datum", "sehr zufrieden", "zufrieden", "weniger zufrieden", "gar nicht zufrieden"]

GERMAN_MONTHS = {
    "januar": 1, "februar": 2, "märz": 3, "maerz": 3, "april": 4, "mai": 5, "juni": 6,
    "juli": 7, "august": 8, "september": 9, "oktober": 10, "november": 11, "dezember": 12,
}

session = requests.Session()
session.headers["User-Agent"] = USER_AGENT


# ===========================================================================
# Part 1: collect PDF links and download the PDFs
# ===========================================================================

def fetch(url: str) -> requests.Response | None:
    """GET a URL with retries. Returns None for 404 or if all retries fail."""
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            response = session.get(url, timeout=REQUEST_TIMEOUT)
            time.sleep(REQUEST_DELAY)
            if response.status_code == 404:
                return None
            response.raise_for_status()
            return response
        except requests.RequestException as exc:
            print(f"  Request failed ({attempt}/{MAX_RETRIES}) for {url}: {exc}")
            time.sleep(2 ** attempt)
    return None


def fetch_soup(url: str) -> BeautifulSoup | None:
    response = fetch(url)
    return BeautifulSoup(response.text, "html.parser") if response else None


def parse_german_date(text: str) -> date | None:
    """Find the first date in the format dd.mm.yyyy in a text."""
    match = re.search(r"(\d{2})\.(\d{2})\.(\d{4})", text)
    if not match:
        return None
    day, month, year = map(int, match.groups())
    return date(year, month, day)


def article_publication_date(soup: BeautifulSoup) -> date | None:
    """Publication date of an article page (meta tag, fallback: first date in the text)."""
    meta = soup.find("meta", attrs={"name": "date"})
    if meta and meta.get("content"):
        try:
            return datetime.fromisoformat(meta["content"][:19]).date()
        except ValueError:
            pass
    return parse_german_date(soup.get_text(" "))


def is_pdf_link(url: str) -> bool:
    return urlparse(url).path.lower().endswith(".pdf")


def is_article_link(url: str) -> bool:
    """DeutschlandTrend article pages on tagesschau.de (archive pages excluded)."""
    parsed = urlparse(url)
    return (
        parsed.netloc.endswith("tagesschau.de")
        and "deutschlandtrend" in parsed.path
        and parsed.path.endswith(".html")
        and "/archiv" not in parsed.path
    )


def listing_pages() -> list[str]:
    """Overview page plus all yearly archive pages from FIRST_YEAR on.

    The available archive years are read from the links on the overview page,
    so new archive years are picked up automatically. Only if no such link is
    found, every year up to last year is tried.
    """
    years: set[int] = set()
    soup = fetch_soup(OVERVIEW_URL)
    if soup:
        for link in soup.find_all("a", href=True):
            match = re.search(r"/deutschlandtrend/archiv/(\d{4})", link["href"])
            if match:
                years.add(int(match.group(1)))
    if not years:
        years = set(range(FIRST_YEAR, date.today().year))
    return [OVERVIEW_URL] + [ARCHIVE_URL.format(year=y) for y in sorted(years) if y >= FIRST_YEAR]


def collect_pdf_links() -> dict[str, date]:
    """Return {pdf_url: publication date} for all DeutschlandTrend PDFs found.

    A PDF can be linked from several pages; the earliest publication date wins.
    """
    pdf_dates: dict[str, date] = {}
    article_urls: set[str] = set()

    def remember(pdf_url: str, published: date | None) -> None:
        if published is None:
            return
        if pdf_url not in pdf_dates or published < pdf_dates[pdf_url]:
            pdf_dates[pdf_url] = published

    # Step 1: listing pages (overview + archive). Some archive years link the
    # PDFs directly below a teaser, the date is taken from that teaser.
    for page_url in listing_pages():
        soup = fetch_soup(page_url)
        if soup is None:
            print(f"Listing page not available, skipped: {page_url}")
            continue
        print(f"Scanning listing page: {page_url}")
        for link in soup.find_all("a", href=True):
            url = urljoin(BASE_URL, link["href"]).split("#")[0]
            if is_pdf_link(url):
                teaser_date = link.find_previous(class_="teaser__date")
                remember(url, parse_german_date(teaser_date.get_text()) if teaser_date else None)
            elif is_article_link(url):
                article_urls.add(url)

    # Step 2: article pages, most PDFs are only linked there.
    print(f"Scanning {len(article_urls)} article pages for PDF links ...")
    for index, article_url in enumerate(sorted(article_urls), start=1):
        soup = fetch_soup(article_url)
        if soup is None:
            continue
        published = article_publication_date(soup)
        for link in soup.find_all("a", href=True):
            url = urljoin(BASE_URL, link["href"]).split("#")[0]
            if is_pdf_link(url):
                remember(url, published)
        if index % 50 == 0:
            print(f"  {index}/{len(article_urls)} article pages scanned")

    return pdf_dates


def download_pdfs(pdf_dates: dict[str, date], target_dir: Path) -> None:
    """Download all PDFs published on/after MIN_PUBLICATION_DATE that are not on disk yet."""
    target_dir.mkdir(parents=True, exist_ok=True)
    wanted = {url: d for url, d in pdf_dates.items() if d >= MIN_PUBLICATION_DATE}
    print(f"{len(wanted)} PDFs published since {MIN_PUBLICATION_DATE:%d.%m.%Y} found.")

    downloaded = skipped = failed = 0
    for url, published in sorted(wanted.items(), key=lambda item: item[1]):
        target = target_dir / Path(urlparse(url).path).name
        if target.exists() and target.stat().st_size > 0:
            skipped += 1
            continue
        response = fetch(url)
        if response is None or not response.content.startswith(b"%PDF"):
            print(f"  Download failed: {url}")
            failed += 1
            continue
        # Write to a temporary file first so an interrupted download never
        # leaves a broken PDF that would be skipped on the next run.
        tmp = target.with_suffix(".part")
        tmp.write_bytes(response.content)
        tmp.replace(target)
        downloaded += 1
        print(f"  Downloaded {target.name} (published {published:%d.%m.%Y})")

    print(f"Download finished: {downloaded} new, {skipped} already present, {failed} failed.")


# ===========================================================================
# Part 2: extract the satisfaction values from the PDFs
# ===========================================================================

# The question in its different wordings ("neuen", "(neuen)"). Variants such as
# "... Bundesregierung unter Führung von Angela Merkel?" or "... in den
# folgenden Bereichen?" do not match because "?" must follow directly.
QUESTION_RE = re.compile(
    r"Wie zufrieden sind Sie mit der Arbeit der (?:\(?neuen\)? )?Bundesregierung\s*\?", re.IGNORECASE
)
# Every slide starts with a header like "ARD-DeutschlandTREND März 2026".
SLIDE_HEADER_RE = re.compile(r"^ARD-DeutschlandTREND", re.IGNORECASE)
# Values are plain integers; changes are signed ("+4", "-1", "±0") or in brackets.
VALUE_RE = re.compile(r"^\d{1,3}$")
# Changes in brackets as used in the older PDFs: "(+4)", "(-6)", "(+/-0)", "(±0)".
CHANGE_RE = re.compile(r"\((\+/-|±|\+|-)?(\d{1,2})\)")
MONTH_NAMES_RE = "|".join(GERMAN_MONTHS)
MONTH_YEAR_RE = re.compile(rf"({MONTH_NAMES_RE})\s+(\d{{4}})", re.IGNORECASE)
# Regular monthly edition in the title, e.g. "ARD-DeutschlandTREND: Mai 2015".
# Additional editions ("September 2013 II", "Oktober II 2024") are excluded.
EDITION_RE = re.compile(
    rf"(?<=DeutschlandTREND)[:\s]*({MONTH_NAMES_RE})\s+(\d{{4}})(?!\s+I{{1,3}}\b)", re.IGNORECASE
)
SURVEY_DATE_RE = re.compile(
    rf"(\d{{1,2}})\.\s*({MONTH_NAMES_RE})\s*(\d{{4}})", re.IGNORECASE
)

# Word tuple layout as returned by pymupdf: (x0, y0, x1, y1, text, block, line, word_no)
Word = tuple


def page_words(page: pymupdf.Page) -> list[Word]:
    """Words of a page in *visual* coordinates.

    Several PDFs use rotated pages (/Rotate 90). pymupdf reports word positions
    in the unrotated coordinate system, so they are transformed here to make
    "above"/"left of" mean the same for every PDF.
    """
    matrix = page.rotation_matrix
    words = []
    for w in page.get_text("words"):
        rect = (pymupdf.Rect(w[:4]) * matrix).normalize()
        words.append((rect.x0, rect.y0, rect.x1, rect.y1) + tuple(w[4:]))
    return words


def question_slides(page: pymupdf.Page, words: list[Word]) -> list[tuple[float, float]]:
    """Vertical ranges (top, bottom) of all slides on a page that contain the question.

    Newer short reports print two slides per page, so the search for the values
    has to be limited to the slide that actually contains the question.
    """
    lines: dict[tuple, list[Word]] = {}
    blocks: dict[int, list[Word]] = {}
    for w in words:
        lines.setdefault((w[5], w[6]), []).append(w)
        blocks.setdefault(w[5], []).append(w)

    header_tops = sorted(
        min(w[1] for w in line)
        for line in lines.values()
        if SLIDE_HEADER_RE.match(min(line, key=lambda w: w[7])[4])
    )

    slides = []
    for block in blocks.values():
        text = " ".join(w[4] for w in sorted(block, key=lambda w: (w[6], w[7])))
        if not QUESTION_RE.search(text):
            continue
        question_top = min(w[1] for w in block)
        top = max([h for h in header_tops if h <= question_top], default=0.0)
        bottom = min([h for h in header_tops if h > question_top], default=page.rect.height + 1)
        if (top, bottom) not in slides:
            slides.append((top, bottom))
    return slides


def category_columns(words: list[Word]) -> tuple[list[float], float, float] | None:
    """Locate the four category labels of the bar chart.

    Returns (x centers of the 4 columns, y of the label row, column distance)
    or None if the slide does not contain the four single categories (e.g. a
    slide with only "sehr zufrieden / zufrieden" aggregates or a time series).
    """
    lines: dict[tuple, list[Word]] = {}
    for w in words:
        lines.setdefault((w[5], w[6]), []).append(w)

    # Anchor words "sehr", "weniger", "gar" of the single-category labels.
    anchors: dict[str, list[tuple[float, float]]] = {"sehr": [], "weniger": [], "gar": []}
    for line in lines.values():
        line.sort(key=lambda w: w[0])
        line_text = " ".join(w[4] for w in line)
        # Skip aggregated labels ("sehr zufrieden / zufrieden"), the question
        # text itself ("... sehr zufrieden, zufrieden, ...?") and long lines.
        if "/" in line_text or "?" in line_text or "," in line_text or len(line) > 6:
            continue
        for i, w in enumerate(line):
            key = w[4].lower()
            if key not in anchors:
                continue
            # The label may continue on the same line ("weniger zufrieden",
            # "gar nicht zufrieden"); its center is the center of all its words.
            j = i
            while j + 1 < len(line) and line[j][4].lower() != "zufrieden" and line[j + 1][4].lower() in ("nicht", "zufrieden"):
                j += 1
            anchors[key].append(((w[0] + line[j][2]) / 2, w[1]))

    # Pick a combination sehr < weniger < gar (left to right) on one row.
    for sehr in anchors["sehr"]:
        for weniger in anchors["weniger"]:
            for gar in anchors["gar"]:
                ys = (sehr[1], weniger[1], gar[1])
                if sehr[0] < weniger[0] < gar[0] and max(ys) - min(ys) < 15:
                    step = (gar[0] - sehr[0]) / 3
                    row_y = min(ys)
                    # The label "zufrieden" is a standalone word between "sehr" and "weniger";
                    # if it cannot be found the columns are assumed to be equally spaced.
                    zufrieden_x = sehr[0] + step
                    for w in words:
                        center = (w[0] + w[2]) / 2
                        if (
                            w[4].lower() == "zufrieden"
                            and sehr[0] + 0.4 * step < center < weniger[0] - 0.4 * step
                            and abs(w[1] - row_y) < 15
                        ):
                            zufrieden_x = center
                    return [sehr[0], zufrieden_x, weniger[0], gar[0]], row_y, step
    return None


def values_from_text(words: list[Word], centers: list[float], row_y: float, step: float) -> list[int | None]:
    """For each column take the integer closest above the label (the bar value)."""
    values: list[int | None] = []
    for center in centers:
        candidates = [
            w for w in words
            if VALUE_RE.match(w[4])
            and abs((w[0] + w[2]) / 2 - center) < 0.4 * step
            and w[3] <= row_y + 3
        ]
        values.append(int(max(candidates, key=lambda w: w[3])[4]) if candidates else None)
    return values


def changes_from_text(words: list[Word], centers: list[float], row_y: float, step: float) -> list[int] | None:
    """Changes to the reference edition printed in brackets above the bars, e.g. "(+4)", "(+/-0)"."""
    changes = []
    for center in centers:
        # Bracket fragments of this column from top to bottom. A change can be
        # split into several text pieces, e.g. "(-" and "5)" on two lines.
        fragments = sorted(
            (w for w in words
             if ("(" in w[4] or ")" in w[4])
             and abs((w[0] + w[2]) / 2 - center) < 0.4 * step
             and w[3] <= row_y + 3),
            key=lambda w: (w[1], w[0]),
        )
        matches = list(CHANGE_RE.finditer("".join(w[4] for w in fragments)))
        if not matches:
            return None
        last = matches[-1]  # the one closest to the label row
        changes.append((-1 if last.group(1) == "-" else 1) * int(last.group(2)))
    return changes


def bar_heights(page: pymupdf.Page, centers: list[float], row_y: float, step: float) -> list[float]:
    """Measure the height of the (blue) bar above every label on the rendered page.

    Used for charts that are embedded as raster images, where the numbers are
    not available as text. Starting at the label row the scan moves upwards to
    the first bar pixel (the axis gap) and counts the contiguous bar pixels.
    """
    zoom = 4
    pix = page.get_pixmap(matrix=pymupdf.Matrix(zoom, zoom), colorspace=pymupdf.csRGB, alpha=False)
    samples, width, n = pix.samples, pix.width, pix.n

    def is_bar_pixel(x: int, y: int) -> bool:
        i = (y * width + x) * n
        r, g, b = samples[i], samples[i + 1], samples[i + 2]
        return b > 100 and b - r > 60 and b - g > 30

    max_gap = 10 * zoom  # maximum distance between label and bar bottom
    heights = []
    for center in centers:
        runs = []
        # A few pixel columns around the center; the median removes outliers.
        for dx in range(-int(0.1 * step * zoom), int(0.1 * step * zoom) + 1, zoom):
            x = min(max(int(center * zoom) + dx, 0), width - 1)
            y = int(row_y * zoom)
            gap = 0
            while y > 0 and not is_bar_pixel(x, y) and gap <= max_gap:
                y -= 1
                gap += 1
            height = 0
            while y > 0 and is_bar_pixel(x, y):
                y -= 1
                height += 1
            runs.append(height)
        heights.append(median(runs) / zoom)
    return heights


def scale_bar_heights(heights: list[float], total: int) -> list[int] | None:
    """Convert bar heights into percentages that add up to `total`."""
    if sum(heights) == 0:
        return None
    return [round(h * total / sum(heights)) for h in heights]


def plausible(values: list[int | None] | None) -> bool:
    """Four values that add up to (at most) 100 percent (+1 for rounding)."""
    return bool(values) and None not in values and 60 <= sum(values) <= 101


@dataclass
class Reading:
    """Result of reading one PDF.

    Either `values` is set (numbers available as text) or the chart is a
    raster image; then the values are derived later from the reference edition
    plus the printed changes, or from the bar heights.
    """
    pdf_name: str
    end_date: date
    edition: tuple[int, int] | None  # (year, month) of the edition, e.g. "Mai 2015"
    page_no: int
    values: list[int] | None = None
    changes: list[int] | None = None
    reference: tuple[int, int] | None = None  # edition the changes refer to
    dont_know: int | None = None  # "Weiß nicht / keine Angabe: N"
    heights: list[float] | None = None


def month_year(text: str) -> tuple[int, int] | None:
    """Parse "Mai 2015" -> (2015, 5)."""
    match = MONTH_YEAR_RE.search(text)
    if not match:
        return None
    return int(match.group(2)), GERMAN_MONTHS[match.group(1).lower()]


def read_pdf(doc: pymupdf.Document, pdf_name: str) -> Reading | None:
    """Find the slide with the four categories and read it. None if the question is missing."""
    end_date = survey_end_date(doc)
    edition_match = EDITION_RE.search(doc[0].get_text())
    edition = month_year(edition_match.group(0)) if edition_match else None

    question_found = False
    for page_no, page in enumerate(doc):
        words = page_words(page)
        for top, bottom in question_slides(page, words):
            question_found = True
            slide_words = [w for w in words if top - 1 <= w[1] and w[3] <= bottom + 1]
            columns = category_columns(slide_words)
            if columns is None:
                continue
            if end_date is None:
                print(f"  {pdf_name}: survey period not found, skipped")
                return None
            centers, row_y, step = columns
            reading = Reading(pdf_name, end_date, edition, page_no)

            values = values_from_text(slide_words, centers, row_y, step)
            if plausible(values):
                reading.values = values
                return reading
            if any(v is not None for v in values):
                continue  # numbers present but not usable (e.g. a time series)

            # Raster chart: collect everything needed to reconstruct the values.
            slide_text = " ".join(w[4] for w in slide_words)
            reference = re.search(r"Vergleich zu\s+(\S+\s+\d{4})", slide_text)
            dont_know = re.search(r"keine Angabe:\s*(\d+)", slide_text)
            reading.changes = changes_from_text(slide_words, centers, row_y, step)
            reading.reference = month_year(reference.group(1)) if reference else None
            reading.dont_know = int(dont_know.group(1)) if dont_know else None
            reading.heights = bar_heights(page, centers, row_y, step)
            return reading

    if question_found:
        print(f"  {pdf_name}: question found, but no values for the four categories, skipped")
    else:
        print(f"  {pdf_name}: question not included, skipped")
    return None


def resolve_raster_reading(reading: Reading, editions: dict[tuple[int, int], list[int]]) -> tuple[list[int], str] | None:
    """Derive the values of a raster chart.

    1. exact: values of the reference edition + printed changes
    2. approximate: bar heights scaled to 100 - "weiß nicht"
    """
    if reading.changes and reading.reference in editions:
        values = [ref + change for ref, change in zip(editions[reading.reference], reading.changes)]
        # Cross-check with the measured bars; a large deviation means the
        # reference edition or the changes were not read correctly.
        estimate = scale_bar_heights(reading.heights or [], sum(values))
        if estimate and max(abs(a - b) for a, b in zip(values, estimate)) > 3:
            print(f"  {reading.pdf_name}: values {values} do not match the bar heights {estimate}, skipped")
            return None
        return values, "reference edition + changes"
    if reading.dont_know is not None:
        values = scale_bar_heights(reading.heights or [], 100 - reading.dont_know)
        if values:
            return values, "bar heights"
    print(f"  {reading.pdf_name}: chart is an image and cannot be reconstructed, skipped")
    return None


def survey_end_date(doc: pymupdf.Document) -> date | None:
    """Last day of the survey period ("Erhebungszeitraum").

    Formats: "28. bis 30. Januar 2013", "29. April bis 1. Mai 2013",
    "12. - 13. November 2018", "03. bis 04.September 2024". The first date
    with a year after the label is the end date. In the newer short reports
    the value stands *before* the label, which is handled as fallback.
    """
    for page in doc:
        text = page.get_text()
        pos = text.find("Erhebungszeitraum")
        if pos < 0:
            continue
        match = SURVEY_DATE_RE.search(text, pos, pos + 120)
        if not match:
            before = list(SURVEY_DATE_RE.finditer(text, max(0, pos - 60), pos))
            match = before[-1] if before else None
        if match:
            day, month, year = match.groups()
            return date(int(year), GERMAN_MONTHS[month.lower()], int(day))
    return None


def build_table(pdf_dir: Path) -> list[list]:
    """Extract one row per survey from all PDFs in pdf_dir."""
    pdf_files = sorted(pdf_dir.glob("*.pdf"))
    print(f"Extracting values from {len(pdf_files)} PDFs in {pdf_dir} ...")

    readings: list[Reading] = []
    for pdf_path in pdf_files:
        try:
            doc = pymupdf.open(pdf_path)
        except Exception as exc:  # corrupt or unreadable file
            print(f"  {pdf_path.name}: cannot be opened ({exc}), skipped")
            continue
        with doc:
            reading = read_pdf(doc, pdf_path.name)
        if reading is not None:
            readings.append(reading)

    # Chronological order, so that the reference edition of a raster chart has
    # already been processed when the chart is resolved.
    readings.sort(key=lambda r: r.end_date)
    rows: dict[date, list] = {}
    editions: dict[tuple[int, int], list[int]] = {}
    for reading in readings:
        if reading.values is not None:
            values, method = reading.values, "text"
        else:
            resolved = resolve_raster_reading(reading, editions)
            if resolved is None:
                continue
            values, method = resolved

        if reading.edition and reading.edition not in editions:
            editions[reading.edition] = values
        if reading.end_date in rows:
            if rows[reading.end_date][1:] != values:
                print(f"  {reading.pdf_name}: different values for {reading.end_date} already stored, kept the first")
            continue
        rows[reading.end_date] = [reading.end_date.isoformat(), *values]
        print(f"  {reading.pdf_name}: {reading.end_date} -> {values} (page {reading.page_no + 1}, {method})")

    return [rows[key] for key in sorted(rows)]


def write_csv(rows: list[list], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(CSV_HEADER)
        writer.writerows(rows)
    print(f"{len(rows)} rows written to {path}")


# ===========================================================================
# Entry point
# ===========================================================================

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    parser.add_argument("--no-download", action="store_true", help="skip the crawling/download step")
    args = parser.parse_args()

    if not args.no_download:
        print("Step 1: collecting PDF links from tagesschau.de ...")
        download_pdfs(collect_pdf_links(), RAW_DIR)

    print("Step 2: extracting satisfaction with the federal government ...")
    rows = build_table(RAW_DIR)
    if not rows:
        print("No values extracted - nothing written.")
        return 1
    write_csv(rows, OUTPUT_CSV)
    return 0


if __name__ == "__main__":
    sys.exit(main())
